CREATE TABLE CUSTOM_RUGS(
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    DETAILS VARCHAR(255) NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)